# This is a basic workflow to help you get started with Actions1111

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install --upgrade pip
          pip install flake8 isort black pytest flask celery flask_sqlalchemy uuid base64
          ls -la
          flake8 .
          isort --line-length 80 --check .
          black --line-length 80 --check .
          py.test tests
